--- 
backend: 
  branch: master
  name: github
  repo: AndreBClark/gatsby-personal-starter-blog
collections: 
  - 
    create: true
    fields: 
      - 
        label: Path
        name: path
      - 
        label: Date
        name: date
        widget: date
      - 
        label: Title
        name: title
      - 
        label: Description
        name: description
      - 
        label: Body
        name: body
        widget: markdown
    folder: content/blog
    label: Blog
    name: blog
  - 
    create: true
    fields: 
      - 
        label: "Character Name"
        name: charname
        widget: string
      - 
        label: Class
        name: class
        options: 
          - Barbarian
          - Cleric
          - Bard
          - Fighter
          - Wizard
          - Warlock
          - Sorcerer
          - Druid
          - Rogue
          - Monk
          - Paladin
          - Ranger
        widget: select
      - 
        label: Level
        max: 20
        min: 1
        name: level
        valueType: int
        widget: number
      - 
        label: Race
        name: race
        options: 
          - Dwarf
          - Elf
          - Halfling
          - Human
          - Dragonborn
          - Gnome
          - Half-Elf
          - Half-Orc
          - Tiefling
        widget: select
      - 
        label: Alignment
        name: alignment
        options: 
          - "Lawful Good"
          - "Neutral Good"
          - "Chaotic Good"
          - "Lawful Neutral"
          - "True Neutral"
          - "Chaotic Neutral"
          - "Lawful Evil"
          - "Neutral Evil"
          - "Chaotic Evil"
        widget: select
    folder: content/character
    label: Character
    name: character
media_folder: static/assets
public_folder: assets