backend:
  name: github
  branch: master
  repo: AndreBClark/gatsby-personal-starter-blog

media_folder: src/images
public_folder: images

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - {
          name: featuredimage,
          "Featured Image",
          widget: image,
          default: "src/images/orbital-bw.jpg",
        }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
